ktor:
    application:
        modules:
            - com.bittokazi.example.ktor.ApplicationKt.module
    deployment:
        port: 8080

database:
  url: ${DB_URL}
  driver: "org.postgresql.Driver"
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

tenants:
  - domain: localhost:8080
    databaseSchema: "public"
    name: "Ktor Auth Server"
  - domain: tenant1.auth.test.local
    databaseSchema: "tenant_one"
    name: "Tenant One"

jwk:
  key-id: "my-key-id"
  private-key-path: certificates/default_private_key_pkcs8.pem
  public-key-path: certificates/default_public_key.pem

oauth:
  session:
    encryption-key: dd78055a2c57f50a636efe0e034764e3 # has to be 32 character. set your own
    signing-key: a94f3c2e8b7f5d4c1e0296a1b3d8f7e3 # has to be 32 character. set your own